src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_res = null;
    
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    /**
 * @Assert\GreaterThanOrEqual(value="today", message="La date de début ne peut pas être antérieure à aujourd'hui.")
 */
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    /**
     * @Assert\Expression(
     *     "this.getDateFin() >= this.getDateDebut()",
     *     message="La date de fin doit être ultérieure à la date de début."
     * )
     */
     private ?\DateTimeInterface $date_fin = null;

    #[ORM\OneToOne(mappedBy: 'reservation', targetEntity: Facture::class)]
    private ?Facture $facture = null;

    #[ORM\OneToOne(inversedBy: 'reservation', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: 'id_v', referencedColumnName: 'id_v', nullable: false)]
    private ?Voiture $id_v = null;

    #[ORM\OneToOne(inversedBy: 'reservation', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: 'id_cl', referencedColumnName: 'id', nullable: false)]
    private ?Utilisateur $id_cl;


    public function getId_res(): ?int
    {
        return $this->id_res;
    }
    

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

   /* public function getFacture(): ?Facture
    {
        return $this->facture;
    }*/

    /*public function setFacture(?Facture $facture): static
    {
        $this->facture = $facture;

        return $this;
    }*/

    public function getIdV(): ?Voiture
    {
        return $this->id_v;
    }

    public function setIdv(?Voiture $id_v): static
    {
        $this->id_v = $id_v;

        return $this;
    }
    

    public function getIdCl(): ?Utilisateur
    {
        return $this->id_cl;
    }

    public function setIdCl(?Utilisateur $id_cl): static
    {
        $this->id_cl = $id_cl;

        return $this;
    }
    public function __toString()
    {
        return $this->id_res;
    }
    
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\DateTime;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut', DateTimeType::class, [
                'date_widget'=> 'single_text'
            ])
            ->add('date_fin', DateTimeType::class, [
                'date_widget'=> 'single_text'
            ])
            //->add('facture')
            ->add('id_v')
            ->add('id_cl')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\Utilisateur;
use App\Entity\Voiture;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use App\Repository\VoitureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

       // $voiture = $voitureRepository->find($id_v);
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request); 
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);

            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id_res}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id_res}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id_res}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId_res(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id_res': reservation.id_res}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id_res) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
<div class="container">
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}


<div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.date_debut, "Date debut")  }}
    {{ form_widget(form.date_debut,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.date_debut) is not empty %}
    <div class="alert alert-danger"
    {{ form_errors(form.date_debut) }}
    </div>
    {% endif %}
    </div>

    <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.date_fin, "Date Fin")  }}
    {{ form_widget(form.date_fin,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.date_fin) is not empty %}
    <div class="alert alert-danger"
    {{ form_errors(form.date_fin) }}
    </div>
    {% endif %}
    </div>

    <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.id_v, "Voiture")  }}
    {{ form_widget(form.id_v,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.id_v) is not empty %}
    <div class="alert alert-danger"
    {{ form_errors(form.id_v) }}
    </div>
    {% endif %}
    </div> 

    <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.id_cl, "Utulisateur")  }}
    {{ form_widget(form.id_cl,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.id_cl) is not empty %}
    <div class="alert alert-danger"
    {{ form_errors(form.id_cl) }}
    </div>
    {% endif %}
    </div>




 <button class="btn btn-primary submit-btn"> 
     {{ button_label|default('Save') }}
    </button>



 {{ form_end(form) }}
</div>

templates/reservation/edit.html.twig
{% extends 'frontt.html.twig' %}


{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'frontt.html.twig' %}


{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Mes reservations</h1>

    <table class="table" border="2">
        <thead>
            <tr>
                {#<th>Id_res</th>#}
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                {#<td>{{ reservation.id_res }}</td>#}
                <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_reservation_show', {'id_res': reservation.id_res}) }}">View</a>
                    <a href="{{ path('app_reservation_edit', {'id_res': reservation.id_res}) }}">Editer</a>
                     
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/indexback.html.twig
{% extends 'back.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Reservation index</h1>

    <input type="text" class="form-control" id="searchInput" placeholder="Search&hellip;">

<br>
<script>
        function filterTable() {
            const filter = document.getElementById('searchInput').value.toUpperCase();
            const rows = document.querySelectorAll('table tr');
            for (let i = 1; i < rows.length; i++) {
                const cols = rows[i].querySelectorAll('td');
                let visible = false;
                for (let j = 0; j < cols.length; j++) {
                    const cell = cols[j];
                    if (cell.innerText.toUpperCase().indexOf(filter) > -1) {
                        visible = true;
                        break;
                    }
                }
                rows[i].style.display = visible ? '' : 'none';
            }
        }
        document.getElementById('searchInput').addEventListener('keyup', filterTable);
    </script>
    <table class="table" border="2">
        <thead>
            <tr>
                <th>Id_res</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
               {#} <th>actions</th> #}
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id_res }}</td>
                <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d') : '' }}</td>
              
                   {#} <a href="{{ path('app_reservation_show', {'id_res': reservation.id_res}) }}">show</a>#}
                   {#} <a href="{{ path('app_reservation_edit', {'id_res': reservation.id_res}) }}">edit</a>#}
               
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   {#} <a href="{{ path('app_reservation_new') }}">Create new</a>#}
{% endblock %}

templates/reservation/new.html.twig
{% extends 'frontt.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    

					
    
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'front.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
<center>  
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Numero reservation</th>
                <td>{{ reservation.id_res }}</td>
            </tr>
            <tr>
                <th>Date debut de reservation</th>
                <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date fin de reservation</th>
                <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    {#<a href="{{ path('app_reservation_index') }}">back to list</a>#}

    <a href="{{ path('app_reservation_edit', {'id_res': reservation.id_res} )  }}" class="btn btn-primary submit-btn">editer</a>

    {{ include('reservation/_delete_form.html.twig') }}
    </center>
{% endblock %}