src/Entity/FicheTechnique.php
<?php

namespace App\Entity;

use App\Repository\FicheTechniqueRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FicheTechniqueRepository::class)]
class FicheTechnique
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_ft = null;

    

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $tax = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $assurence = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $visite_tech = null;

    #[ORM\Column(length: 255)]
    private ?string $vidange = null;

    #[ORM\OneToOne(inversedBy: 'ficheTechnique', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: 'id_v', referencedColumnName: 'id_v', nullable: false)]
    private ?Voiture $id_v = null;

  

    public function getId(): ?int
    {
        return $this->id_ft;
    }

    

    

    public function getTax(): ?\DateTimeInterface
    {
        return $this->tax;
    }

    public function setTax(\DateTimeInterface $tax): static
    {
        $this->tax = $tax;

        return $this;
    }

    public function getAssurence(): ?\DateTimeInterface
    {
        return $this->assurence;
    }

    public function setAssurence(\DateTimeInterface $assurence): static
    {
        $this->assurence = $assurence;

        return $this;
    }

    public function getVisiteTech(): ?\DateTimeInterface
    {
        return $this->visite_tech;
    }

    public function setVisiteTech(\DateTimeInterface $visite_tech): static
    {
        $this->visite_tech = $visite_tech;

        return $this; 
    }

    public function getVidange(): ?string
    {
        return $this->vidange;
    }

    public function setVidange(string $vidange): static
    {
        $this->vidange = $vidange;

        return $this;
    }

    public function getIdV(): ?Voiture
    {
        return $this->id_v;
    }

    public function setIdV(?Voiture $id_v): static
    {
        $this->id_v = $id_v;

        return $this;
    }

   
}

src/Form/FicheTechniqueType.php
<?php

namespace App\Form;

use App\Entity\FicheTechnique;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FicheTechniqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            //->add('id') 
            ->add('tax')
            ->add('assurence')
            ->add('visite_tech')
            ->add('vidange')
            ->add('id_v')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FicheTechnique::class,
        ]);
    }
}

src/Controller/FicheTechniqueController.php
<?php

namespace App\Controller;

use App\Entity\FicheTechnique;
use App\Form\FicheTechniqueType;
use App\Repository\FicheTechniqueRepository;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/fiche/technique')]
class FicheTechniqueController extends AbstractController
{
    #[Route('/', name: 'app_fiche_technique_index', methods: ['GET'])]
    public function index(FicheTechniqueRepository $ficheTechniqueRepository): Response
    {
        return $this->render('fiche_technique/index.html.twig', [
            'fiche_techniques' => $ficheTechniqueRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_fiche_technique_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $ficheTechnique = new FicheTechnique();
        $form = $this->createForm(FicheTechniqueType::class, $ficheTechnique);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($ficheTechnique);
            $entityManager->flush();

            return $this->redirectToRoute('app_fiche_technique_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fiche_technique/new.html.twig', [
            'fiche_technique' => $ficheTechnique,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_technique_show', methods: ['GET'])]
    public function show(FicheTechnique $ficheTechnique): Response
    {
        return $this->render('fiche_technique/show.html.twig', [
            'fiche_technique' => $ficheTechnique,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fiche_technique_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FicheTechnique $ficheTechnique, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FicheTechniqueType::class, $ficheTechnique);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_fiche_technique_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fiche_technique/edit.html.twig', [
            'fiche_technique' => $ficheTechnique,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_technique_delete', methods: ['POST'])]
    public function delete(Request $request, FicheTechnique $ficheTechnique, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ficheTechnique->getId(), $request->request->get('_token'))) {
            $entityManager->remove($ficheTechnique);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_fiche_technique_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/fichse/technique/{id}/pdf', name: 'PDF_t')]
    public function generatePdf($id,FicheTechniqueRepository $ficheRepository,FicheTechnique $fiche, Request $request)
    {
        // Récupération des données de la facture par ID
        $fiche = $ficheRepository->find($id);

        
        // Génération du document PDF
        $dompdf = new Dompdf();
        $dompdf->loadHtml($this->renderView('fiche_technique/pdffiche.html.twig',
         ['fiche' => $fiche]));
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        // Envoi du PDF en tant que réponse HTTP
        //$response = new Response();
        //$response->setContent($dompdf->output());
        //$response->headers->set('Content-Type', 'application/pdf');
        //$response->headers->set('Content-Disposition', 'inline; filename="facture.pdf"');

        // Output the generated PDF to Browser (inline view)
        // Send the PDF to the browser
        $response = new Response($dompdf->output(), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="VotreFiche.pdf"',
        ]);

        return $response;
    }
}

templates/fiche_technique/_delete_form.html.twig
<form method="post" action="{{ path('app_fiche_technique_delete', {'id': fiche_technique.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche_technique.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fiche_technique/_form.html.twig
<div class="container">
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}



    <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.tax, "tax")  }}
    {{ form_widget(form.tax,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.tax) is not empty %}
    <div class="alert alert-danger">
    {{ form_errors(form.tax) }}
    </div>
    {% endif %}
    </div>

    <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.assurence, "assurance")  }}
    {{ form_widget(form.assurence,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.assurence) is not empty %}
    <div class="alert alert-danger">
    {{ form_errors(form.assurence) }}
    </div>
    {% endif %}
    </div>

    <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.visite_tech, "visite technique")  }}
    {{ form_widget(form.visite_tech,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.visite_tech) is not empty %}
    <div class="alert alert-danger">
    {{ form_errors(form.visite_tech) }}
    </div>
    {% endif %}
    </div>

     <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.vidange, "vidange")  }}
    {{ form_widget(form.vidange,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.vidange) is not empty %}
    <div class="alert alert-danger">
    {{ form_errors(form.vidange) }}
    </div>
    {% endif %}
    </div>

    <div class="col-md-6 col-sm-12">
    <div class="form-group card-label">
    {{ form_label(form.id_v, "voiture")  }}
    {{ form_widget(form.id_v,({'class':'form-control'})) }}
    </div>
    {% if form_errors(form.id_v) is not empty %}
    <div class="alert alert-danger">
    {{ form_errors(form.id_v) }}
    </div>
    {% endif %}
    </div>


   





 <button class="btn btn-primary submit-btn"> 
     {{ button_label|default('Save') }}
    </button>



 {{ form_end(form) }}
</div>

templates/fiche_technique/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Edit FicheTechnique{% endblock %}

{% block body %}
    <h1>Edit FicheTechnique</h1>

    {{ include('fiche_technique/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_fiche_technique_index') }}">back to list</a>

    {{ include('fiche_technique/_delete_form.html.twig') }}
{% endblock %}

templates/fiche_technique/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}FicheTechnique index{% endblock %}

{% block body %}
    <h1>FicheTechnique index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tax</th>
                <th>Assurence</th>
                <th>Visite_tech</th>
                <th>Vidange</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fiche_technique in fiche_techniques %}
            <tr>
                <td>{{ fiche_technique.id }}</td>
                <td>{{ fiche_technique.tax ? fiche_technique.tax|date('Y-m-d') : '' }}</td>
                <td>{{ fiche_technique.assurence ? fiche_technique.assurence|date('Y-m-d') : '' }}</td>
                <td>{{ fiche_technique.visiteTech ? fiche_technique.visiteTech|date('Y-m-d') : '' }}</td>
                <td>{{ fiche_technique.vidange }}</td>
                <td>
                    <a href="{{ path('app_fiche_technique_show', {'id': fiche_technique.id}) }}">view</a>
                    <a href="{{ path('app_fiche_technique_edit', {'id': fiche_technique.id}) }}">editer</a>
                <a href="{{ path('PDF_t', {'id': fiche_technique.id}) }}">pdf</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_fiche_technique_new') }}">Create new</a>
{% endblock %}

templates/fiche_technique/indexback.html.twig
{% extends 'back.html.twig' %}


{% block title %}FicheTechnique index{% endblock %}
{% block body %}
    <h1>FicheTechnique index</h1>
  <input type="text" class="form-control" id="searchInput" placeholder="Search&hellip;">

<br>
<script>
        function filterTable() {
            const filter = document.getElementById('searchInput').value.toUpperCase();
            const rows = document.querySelectorAll('table tr');
            for (let i = 1; i < rows.length; i++) {
                const cols = rows[i].querySelectorAll('td');
                let visible = false;
                for (let j = 0; j < cols.length; j++) {
                    const cell = cols[j];
                    if (cell.innerText.toUpperCase().indexOf(filter) > -1) {
                        visible = true;
                        break;
                    }
                }
                rows[i].style.display = visible ? '' : 'none';
            }
        }
        document.getElementById('searchInput').addEventListener('keyup', filterTable);
    </script>
    <table class="table" border="2">
        <thead>
            <tr>
               <th>Id</th>
                
                <th>Tax</th>
                <th>Assurence</th>
                <th>Visite_tech</th>
                <th>Vidange</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
       {% for fiche_technique in fiche_techniques %}
            <tr>
                <td>{{ fiche_technique.id }}</td>
                
                <td>{{ fiche_technique.tax ? fiche_technique.tax|date('Y-m-d') : '' }}</td>
                <td>{{ fiche_technique.assurence ? fiche_technique.assurence|date('Y-m-d') : '' }}</td>
                <td>{{ fiche_technique.visiteTech ? fiche_technique.visiteTech|date('Y-m-d') : '' }}</td>
                <td>{{ fiche_technique.vidange }}</td>
                <td>
                   {#} <a href="{{ path('app_fiche_technique_show', {'id': fiche_technique.id}) }}">view</a>{#}
                    {#}<a href="{{ path('app_fiche_technique_edit', {'id': fiche_technique.id}) }}">editer</a>#}
                       <a href="{{ path('PDF_t', {'id': fiche_technique.id}) }}">pdf</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   {#} <a href="{{ path('app_fiche_technique_new') }}">Create new</a> #}
{% endblock %}

templates/fiche_technique/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}New FicheTechnique{% endblock %}

{% block body %}
    <h1>Create new FicheTechnique</h1>

    {{ include('fiche_technique/_form.html.twig') }}

    <a href="{{ path('app_fiche_technique_index') }}">back to list</a>
{% endblock %}

templates/fiche_technique/pdffiche.html.twig
    
<center> <h3>Votre fiche</h3> </center>


<table class="table">
        <tbody>
            <tr>
                <th>Numero fiche est :</th>
                <td>{{ fiche.id }}</td>
            </tr>

            <p>Entreprise LOCATOUR</p>
 <p>  Adresse postale : 1.2 rue andré ampere - 2083 - Pole Technologique Ghazela</p>
 <p>  Adresse e-mail : LOCATOUR125@gmail.com</p>
  <p> Telephone : +216 00 000 000</p>
            
           
            
        </tbody>
    </table>

<br>
<br>
<br>
<br>
</div>

templates/fiche_technique/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}FicheTechnique{% endblock %}

{% block body %}
<center>
    <h1>FicheTechnique</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fiche_technique.id }}</td>
            </tr>
            
           
            <tr>
                <th>Tax</th>
                <td>{{ fiche_technique.tax ? fiche_technique.tax|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Assurence</th>
                <td>{{ fiche_technique.assurence ? fiche_technique.assurence|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Visite_tech</th>
                <td>{{ fiche_technique.visiteTech ? fiche_technique.visiteTech|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Vidange</th>
                <td>{{ fiche_technique.vidange }}</td>
            </tr>
        </tbody>
    </table>

     {#<a href="{{ path('app_fiche_technique_index') }}">back to list</a>#}

    <a href="{{ path('app_fiche_technique_edit', {'id': fiche_technique.id}) }}"class="btn btn-primary submit-btn">edit</a>

    {{ include('fiche_technique/_delete_form.html.twig') }}
    </center>
{% endblock %}